#!/usr/bin/env python3
"""PreToolUse hook — block writes to sensitive files.

Handles both single-file tools (Claude Code Write/Edit, Gemini write_file) and
patch-based tools (Codex apply_patch, which may touch multiple files per call).

Configuration (~/.claude/hook-config.json, fileProtector section):
  protectedPatterns  — list of regex strings; matched files are blocked (exit 2)
  lockFilePatterns   — list of regex strings; matched files emit a warning (exit 0)

Falls back to hardcoded defaults when the config file is absent or malformed.

Exit codes:
  0  allow
  2  block (stderr message forwarded to the agent)
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

_CONFIG_FILE = Path.home() / ".claude" / "hook-config.json"

_DEFAULT_PROTECTED: list[str] = [
    r"\.env$",
    r"\.env\.",
    r"/\.env$",
    r"secrets/",
    r"secret[s]?\.",
    r"\.key$",
    r"\.pem$",
    r"\.p12$",
    r"\.pfx$",
    r"\.ssh/",
    r"id_rsa",
    r"id_ed25519",
    r"credentials",
    r"password",
    r"\.secret$",
    r"api[_-]?key",
    r"auth[_-]?token",
]

_DEFAULT_LOCKS: list[str] = [
    r"package-lock\.json$",
    r"yarn\.lock$",
    r"pnpm-lock\.yaml$",
    r"go\.sum$",
    r"Cargo\.lock$",
    r"poetry\.lock$",
    r"Gemfile\.lock$",
    r"composer\.lock$",
]

# Patch header patterns for apply_patch (Codex custom format + unified diff)
_PATCH_FILE_RE = re.compile(
    r"^\*\*\* (?:Update|Add|Delete) File: (.+)$|^\+\+\+ b/(.+)$",
    re.MULTILINE,
)


def _load_patterns(section: str, default: list[str]) -> list[str]:
    if not _CONFIG_FILE.is_file():
        return default
    try:
        cfg = json.loads(_CONFIG_FILE.read_text())
        patterns = cfg.get("fileProtector", {}).get(section, None)
        return patterns if patterns is not None else default
    except (json.JSONDecodeError, OSError):
        return default


def _extract_patch_paths(patch: str) -> list[str]:
    """Extract all file paths touched by an apply_patch patch string."""
    paths = []
    for m in _PATCH_FILE_RE.finditer(patch):
        paths.append(m.group(1) or m.group(2))
    return paths


def _check_path(
    path: str,
    protected: list[str],
    locks: list[str],
) -> None:
    """Check one path; exits 2 if protected, prints warning if lock file."""
    for pattern in protected:
        if re.search(pattern, path):
            print(f"BLOCKED: Cannot modify sensitive file: {path}", file=sys.stderr)
            print(f"Pattern matched: {pattern}", file=sys.stderr)
            print(
                "To customize: edit ~/.claude/hook-config.json"
                " (fileProtector.protectedPatterns)",
                file=sys.stderr,
            )
            sys.exit(2)

    for pattern in locks:
        if re.search(pattern, path):
            print(f"WARNING: Modifying lock file: {path}", file=sys.stderr)
            print(
                "Lock files should typically be auto-generated by package managers",
                file=sys.stderr,
            )
            return


def main() -> None:
    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except json.JSONDecodeError:
        sys.exit(0)

    tool_input = payload.get("tool_input", {})
    protected = _load_patterns("protectedPatterns", _DEFAULT_PROTECTED)
    locks = _load_patterns("lockFilePatterns", _DEFAULT_LOCKS)

    # Single-file tools: Write, Edit, MultiEdit (Claude Code / Gemini)
    path = tool_input.get("file_path") or tool_input.get("path") or ""
    if path:
        _check_path(path, protected, locks)
        return

    # Patch-based tools: apply_patch (Codex) — may touch multiple files
    patch = tool_input.get("patch") or ""
    if patch:
        for p in _extract_patch_paths(patch):
            _check_path(p, protected, locks)


if __name__ == "__main__":
    main()
