'use server';

import { db } from '@/lib/db';
import { getAuthUserId } from '@/lib/auth-guard';
import { logger } from '@/lib/logger';
import type { ActionResult } from './types';

const MODULE_META: Record<number, { title: string }> = {
  0: { title: 'Onboarding' },
  1: { title: 'Foundations' },
  4: { title: 'Campaign Architecture' },
  6: { title: 'Bidding Lab' },
  7: { title: 'Search Term Triage' },
};

export async function getCheatSheet(moduleNumber: number): Promise<ActionResult<string>> {
  try {
    const userId = await getAuthUserId();
    if (!userId) return { success: false, error: 'Not authenticated', code: 'UNAUTHENTICATED' };

    const meta = MODULE_META[moduleNumber];
    if (!meta) return { success: false, error: 'Module not found', code: 'MODULE_NOT_FOUND' };

    // ponytail: collect lesson titles from DB to gate by completion
    const moduleRecord = await db.module.findFirst({ where: { moduleNumber } });
    if (!moduleRecord) return { success: false, error: 'Module not found', code: 'MODULE_NOT_FOUND' };

    const lessons = await db.lesson.findMany({
      where: { moduleId: moduleRecord.id, isPublished: true },
      orderBy: { lessonNumber: 'asc' },
      select: { title: true, lessonNumber: true, estimatedMinutes: true },
    });

    const progress = await db.lessonProgress.findMany({
      where: { userId, lesson: { moduleId: moduleRecord.id }, status: 'COMPLETED' },
      select: { lesson: { select: { lessonNumber: true } } },
    });
    const completedLessons = new Set(progress.map(p => p.lesson.lessonNumber));

    // ponytail: require at least 1 lesson completed to gate
    if (completedLessons.size === 0) {
      return { success: false, error: 'Complete at least one lesson first', code: 'LOCKED' };
    }

    const content = [
      `# ${meta.title} — Cheat Sheet`,
      ``,
      ...lessons.map(l =>
        `## ${l.lessonNumber}. ${l.title}` + (completedLessons.has(l.lessonNumber) ? '' : ' 🔒')
      ),
      ``,
      `---`,
      `Generated by AdCraft PPC Command Center`,
    ].join('\n');

    return { success: true, data: content };
  } catch (error) {
    logger.error('getCheatSheet failed', { error: String(error) });
    return { success: false, error: 'Failed', code: 'CHEATSHEET_ERROR' };
  }
}
